// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/17/2025, 11:45:06 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Kelas 12/PKL/Artefy/artefy-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/plugins/**/*.{js,ts,mjs}","D:/Kelas 12/PKL/Artefy/artefy-frontend/composables/**/*.{js,ts,mjs}","D:/Kelas 12/PKL/Artefy/artefy-frontend/utils/**/*.{js,ts,mjs}","D:/Kelas 12/PKL/Artefy/artefy-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Kelas 12/PKL/Artefy/artefy-frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;