
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AddCommunityModal': typeof import("../components/AddCommunityModal.vue")['default']
    'DynamicRulesForm': typeof import("../components/DynamicRulesForm.vue")['default']
    'JoinRequestsManager': typeof import("../components/JoinRequestsManager.vue")['default']
    'Layout': typeof import("../components/Layout.vue")['default']
    'LeftSidebar': typeof import("../components/LeftSidebar.vue")['default']
    'Modal': typeof import("../components/Modal.vue")['default']
    'ModeratorDashboard': typeof import("../components/ModeratorDashboard.vue")['default']
    'Notifikasi': typeof import("../components/Notifikasi.vue")['default']
    'PostCreate': typeof import("../components/PostCreate.vue")['default']
    'PostList': typeof import("../components/PostList.vue")['default']
    'SuperAdminDashboard': typeof import("../components/SuperAdminDashboard.vue")['default']
    'UserCommunity': typeof import("../components/UserCommunity.vue")['default']
    'UserDashboard': typeof import("../components/UserDashboard.vue")['default']
    'AuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'AuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'CommunityCard': typeof import("../components/community/CommunityCard.vue")['default']
    'CommunityDetail': typeof import("../components/community/CommunityDetail.vue")['default']
    'CommunityJoinDialog': typeof import("../components/community/CommunityJoinDialog.vue")['default']
    'CommunityList': typeof import("../components/community/CommunityList.vue")['default']
    'MainChatInterface': typeof import("../components/main/ChatInterface.vue")['default']
    'MainFeatureSection': typeof import("../components/main/FeatureSection.vue")['default']
    'MainHeroSection': typeof import("../components/main/HeroSection.vue")['default']
    'MainLoginInterface': typeof import("../components/main/LoginInterface.vue")['default']
    'MainRightSidebar': typeof import("../components/main/RightSidebar.vue")['default']
    'MainTheFooter': typeof import("../components/main/TheFooter.vue")['default']
    'MainTheHeader': typeof import("../components/main/TheHeader.vue")['default']
    'NotifikasiJoinRequestsList': typeof import("../components/notifikasi/JoinRequestsList.vue")['default']
    'NotifikasiLoadingSpinner': typeof import("../components/notifikasi/LoadingSpinner.vue")['default']
    'NotifikasiNotificationCenter': typeof import("../components/notifikasi/NotificationCenter.vue")['default']
    'NotifikasiNotificationList': typeof import("../components/notifikasi/NotificationList.vue")['default']
    'UserpostPostCreate': typeof import("../components/userpost/PostCreate.vue")['default']
    'UserpostPostList': typeof import("../components/userpost/PostList.vue")['default']
    'UserpostPostModal': typeof import("../components/userpost/PostModal.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAddCommunityModal': typeof import("../components/AddCommunityModal.vue")['default']
    'LazyDynamicRulesForm': typeof import("../components/DynamicRulesForm.vue")['default']
    'LazyJoinRequestsManager': typeof import("../components/JoinRequestsManager.vue")['default']
    'LazyLayout': typeof import("../components/Layout.vue")['default']
    'LazyLeftSidebar': typeof import("../components/LeftSidebar.vue")['default']
    'LazyModal': typeof import("../components/Modal.vue")['default']
    'LazyModeratorDashboard': typeof import("../components/ModeratorDashboard.vue")['default']
    'LazyNotifikasi': typeof import("../components/Notifikasi.vue")['default']
    'LazyPostCreate': typeof import("../components/PostCreate.vue")['default']
    'LazyPostList': typeof import("../components/PostList.vue")['default']
    'LazySuperAdminDashboard': typeof import("../components/SuperAdminDashboard.vue")['default']
    'LazyUserCommunity': typeof import("../components/UserCommunity.vue")['default']
    'LazyUserDashboard': typeof import("../components/UserDashboard.vue")['default']
    'LazyAuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'LazyAuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'LazyCommunityCard': typeof import("../components/community/CommunityCard.vue")['default']
    'LazyCommunityDetail': typeof import("../components/community/CommunityDetail.vue")['default']
    'LazyCommunityJoinDialog': typeof import("../components/community/CommunityJoinDialog.vue")['default']
    'LazyCommunityList': typeof import("../components/community/CommunityList.vue")['default']
    'LazyMainChatInterface': typeof import("../components/main/ChatInterface.vue")['default']
    'LazyMainFeatureSection': typeof import("../components/main/FeatureSection.vue")['default']
    'LazyMainHeroSection': typeof import("../components/main/HeroSection.vue")['default']
    'LazyMainLoginInterface': typeof import("../components/main/LoginInterface.vue")['default']
    'LazyMainRightSidebar': typeof import("../components/main/RightSidebar.vue")['default']
    'LazyMainTheFooter': typeof import("../components/main/TheFooter.vue")['default']
    'LazyMainTheHeader': typeof import("../components/main/TheHeader.vue")['default']
    'LazyNotifikasiJoinRequestsList': typeof import("../components/notifikasi/JoinRequestsList.vue")['default']
    'LazyNotifikasiLoadingSpinner': typeof import("../components/notifikasi/LoadingSpinner.vue")['default']
    'LazyNotifikasiNotificationCenter': typeof import("../components/notifikasi/NotificationCenter.vue")['default']
    'LazyNotifikasiNotificationList': typeof import("../components/notifikasi/NotificationList.vue")['default']
    'LazyUserpostPostCreate': typeof import("../components/userpost/PostCreate.vue")['default']
    'LazyUserpostPostList': typeof import("../components/userpost/PostList.vue")['default']
    'LazyUserpostPostModal': typeof import("../components/userpost/PostModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'LazyNuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AddCommunityModal: typeof import("../components/AddCommunityModal.vue")['default']
export const DynamicRulesForm: typeof import("../components/DynamicRulesForm.vue")['default']
export const JoinRequestsManager: typeof import("../components/JoinRequestsManager.vue")['default']
export const Layout: typeof import("../components/Layout.vue")['default']
export const LeftSidebar: typeof import("../components/LeftSidebar.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const ModeratorDashboard: typeof import("../components/ModeratorDashboard.vue")['default']
export const Notifikasi: typeof import("../components/Notifikasi.vue")['default']
export const PostCreate: typeof import("../components/PostCreate.vue")['default']
export const PostList: typeof import("../components/PostList.vue")['default']
export const SuperAdminDashboard: typeof import("../components/SuperAdminDashboard.vue")['default']
export const UserCommunity: typeof import("../components/UserCommunity.vue")['default']
export const UserDashboard: typeof import("../components/UserDashboard.vue")['default']
export const AuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const AuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const CommunityCard: typeof import("../components/community/CommunityCard.vue")['default']
export const CommunityDetail: typeof import("../components/community/CommunityDetail.vue")['default']
export const CommunityJoinDialog: typeof import("../components/community/CommunityJoinDialog.vue")['default']
export const CommunityList: typeof import("../components/community/CommunityList.vue")['default']
export const MainChatInterface: typeof import("../components/main/ChatInterface.vue")['default']
export const MainFeatureSection: typeof import("../components/main/FeatureSection.vue")['default']
export const MainHeroSection: typeof import("../components/main/HeroSection.vue")['default']
export const MainLoginInterface: typeof import("../components/main/LoginInterface.vue")['default']
export const MainRightSidebar: typeof import("../components/main/RightSidebar.vue")['default']
export const MainTheFooter: typeof import("../components/main/TheFooter.vue")['default']
export const MainTheHeader: typeof import("../components/main/TheHeader.vue")['default']
export const NotifikasiJoinRequestsList: typeof import("../components/notifikasi/JoinRequestsList.vue")['default']
export const NotifikasiLoadingSpinner: typeof import("../components/notifikasi/LoadingSpinner.vue")['default']
export const NotifikasiNotificationCenter: typeof import("../components/notifikasi/NotificationCenter.vue")['default']
export const NotifikasiNotificationList: typeof import("../components/notifikasi/NotificationList.vue")['default']
export const UserpostPostCreate: typeof import("../components/userpost/PostCreate.vue")['default']
export const UserpostPostList: typeof import("../components/userpost/PostList.vue")['default']
export const UserpostPostModal: typeof import("../components/userpost/PostModal.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAddCommunityModal: typeof import("../components/AddCommunityModal.vue")['default']
export const LazyDynamicRulesForm: typeof import("../components/DynamicRulesForm.vue")['default']
export const LazyJoinRequestsManager: typeof import("../components/JoinRequestsManager.vue")['default']
export const LazyLayout: typeof import("../components/Layout.vue")['default']
export const LazyLeftSidebar: typeof import("../components/LeftSidebar.vue")['default']
export const LazyModal: typeof import("../components/Modal.vue")['default']
export const LazyModeratorDashboard: typeof import("../components/ModeratorDashboard.vue")['default']
export const LazyNotifikasi: typeof import("../components/Notifikasi.vue")['default']
export const LazyPostCreate: typeof import("../components/PostCreate.vue")['default']
export const LazyPostList: typeof import("../components/PostList.vue")['default']
export const LazySuperAdminDashboard: typeof import("../components/SuperAdminDashboard.vue")['default']
export const LazyUserCommunity: typeof import("../components/UserCommunity.vue")['default']
export const LazyUserDashboard: typeof import("../components/UserDashboard.vue")['default']
export const LazyAuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const LazyAuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const LazyCommunityCard: typeof import("../components/community/CommunityCard.vue")['default']
export const LazyCommunityDetail: typeof import("../components/community/CommunityDetail.vue")['default']
export const LazyCommunityJoinDialog: typeof import("../components/community/CommunityJoinDialog.vue")['default']
export const LazyCommunityList: typeof import("../components/community/CommunityList.vue")['default']
export const LazyMainChatInterface: typeof import("../components/main/ChatInterface.vue")['default']
export const LazyMainFeatureSection: typeof import("../components/main/FeatureSection.vue")['default']
export const LazyMainHeroSection: typeof import("../components/main/HeroSection.vue")['default']
export const LazyMainLoginInterface: typeof import("../components/main/LoginInterface.vue")['default']
export const LazyMainRightSidebar: typeof import("../components/main/RightSidebar.vue")['default']
export const LazyMainTheFooter: typeof import("../components/main/TheFooter.vue")['default']
export const LazyMainTheHeader: typeof import("../components/main/TheHeader.vue")['default']
export const LazyNotifikasiJoinRequestsList: typeof import("../components/notifikasi/JoinRequestsList.vue")['default']
export const LazyNotifikasiLoadingSpinner: typeof import("../components/notifikasi/LoadingSpinner.vue")['default']
export const LazyNotifikasiNotificationCenter: typeof import("../components/notifikasi/NotificationCenter.vue")['default']
export const LazyNotifikasiNotificationList: typeof import("../components/notifikasi/NotificationList.vue")['default']
export const LazyUserpostPostCreate: typeof import("../components/userpost/PostCreate.vue")['default']
export const LazyUserpostPostList: typeof import("../components/userpost/PostList.vue")['default']
export const LazyUserpostPostModal: typeof import("../components/userpost/PostModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const LazyNuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
